# 참고. 데이터베이스 조작 ETL

# 1. 오라클 DB에 파일데이터 저장하기

In [20]:
# 라이브러리 정의
import pandas as pd
from sqlalchemy import types
from sqlalchemy import create_engine 

########### 필요 변수 정의 ##################
#테이블 이름 정의
ENCODING = "ms949"
TARGETDATANAME = "kopo_promotion"
DBPREFIX="oracle+cx_oracle"
DBIP="192.168.110.13"
DBID="KOPO"
DBPW="KOPO"
DBPORT="1521"
DBNAME="xe"
VARCHARMAX = 100
########### 필요 변수 정의 ##################

# 데이터 불러오기
# csv파일 불러오기
data = pd.read_csv("../dataset/{}.csv".format(TARGETDATANAME), encoding=ENCODING)
# 오라클 메타데이터에 맞게 컬럼정보 대문자 변환
data.columns = data.columns.str.upper()

# 필수! 성능향상을 위해 데이터베이스의 타입 정의
#data[c].str.len().max() 
targetColumns = list( data.columns[data.dtypes == 'object'] )
targetColumnsLen = len(targetColumns)
typeDict = {}

for i in range(0, targetColumnsLen):
    typeDict[  targetColumns[i]  ] = types.VARCHAR(VARCHARMAX)
# 참고 for문 거꾸로 하는경우
# to_varchar= {c:types.VARCHAR( VARCHARMAX )\
#              for c in data.columns[data.dtypes == 'object'].tolist()}

# DB커넥션 생성
dbconnectingInfo = "{}://{}:{}@{}:{}/{}".format(DBPREFIX,
                                             DBID,
                                             DBPW,
                                             DBIP,
                                             DBPORT,
                                             DBNAME)
                                             
engine = create_engine(dbconnectingInfo) 

# 데이터 저장 
tablename = TARGETDATANAME.upper()
data.to_sql(name=tablename,con=engine, index=False,if_exists="replace",dtype=typeDict)

FileNotFoundError: [Errno 2] No such file or directory: '../dataset/kopo_promotion.csv'

# 1. 오라클 DB에 있는 테이블정보 불러오기

In [15]:
########### 필요 변수 정의 ##################
#테이블 이름 정의
TARGETTABLENAME = "pro_promotion"
########### 필요 변수 정의 ##################

In [16]:
# DB 테이블을 읽어 Data Frame 변수에 저장하기
indata = pd.read_sql_query('SELECT * FROM {}'.format(TARGETTABLENAME), engine)

In [17]:
indata

,regionseg,salesid,productgroup,item,targetweek,planwee,map_price,ir,pmap,pmap10,pro_percent
0,A01,SALESID0001,PG03,ITEM0200,201631,201619,0,278,-278,-251,0.250000
1,A01,SALESID0001,PG04,ITEM0285,201606,201601,3199,756,2443,2199,0.312598
2,A01,SALESID0001,PG04,ITEM0285,201607,201601,3199,756,2443,2199,0.312598
3,A01,SALESID0001,PG04,ITEM0285,201608,201601,3199,756,2443,2199,0.312598
4,A01,SALESID0001,PG04,ITEM0285,201609,201601,3199,533,2666,2399,0.250078
...,...,...,...,...,...,...,...,...,...,...,...
18340,A01,SALESID0001,PG04,ITEM0349,201638,201628,1699,145,1554,1399,0.176574
18341,A01,SALESID0001,PG04,ITEM0281,201638,201628,2899,245,2654,2389,0.175923
18342,A01,SALESID0001,PG04,ITEM0281,201639,201628,2899,245,2654,2389,0.175923
18343,A01,SALESID0001,PG04,ITEM0276,201639,201627,0,78,0,0,0.250000
18344,A01,SALESID0001,PG04,ITEM0246,201639,201628,3999,333,3666,3300,0.174794

In [32]:
# DB 커넥션 열기
engine = create_engine('oracle+cx_oracle://kopo:kopo@58.143.53.136:1521/xe') 

# DB 테이블을 읽어 Data Frame 변수에 저장하기
selloutData = pd.read_sql_query('SELECT * FROM kopo_product_volume', engine)

'C:\\Users\\kopo\\devcode\\Session13 - Database'